{application,nerves_init_gadget,
             [{applications,[kernel,stdlib,elixir,logger,nerves_firmware_ssh,
                             ring_logger,mdns,nerves_runtime,nerves_network]},
              {description,"Simple initialization for devices running Nerves\n"},
              {modules,['Elixir.Nerves.InitGadget',
                        'Elixir.Nerves.InitGadget.Application',
                        'Elixir.Nerves.InitGadget.NetworkManager',
                        'Elixir.Nerves.InitGadget.NetworkManager.State',
                        'Elixir.Nerves.InitGadget.Options',
                        'Elixir.Nerves.InitGadget.SSHConsole']},
              {registered,[]},
              {vsn,"0.4.0"},
              {extra_applications,[logger]},
              {mod,{'Elixir.Nerves.InitGadget.Application',[]}}]}.
